/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { MediaCreateOrder } from "./mediaCreateOrder"

export interface MediaCreate {
  deleted?: boolean;
  filename: string;
  id: string;
  mimetype: string;
  order: MediaCreateOrder;
  originalName: string;
  path: string;
  size: number;
}
