/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { CharacteristicBase } from './characteristicBase';
import type { CharacteristicAllOf } from './characteristicAllOf';

export type Characteristic = CharacteristicBase & CharacteristicAllOf;
