/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * API Admin
 * Category Api
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type AltNameDescriptionOneOf = unknown | null;
