/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * API Admin
 * Category Api
 * OpenAPI spec version: 1.0.0
 */

export * from './altName';
export * from './altNameAllOf';
export * from './altNameBase';
export * from './altNameBaseDescription';
export * from './altNameBaseDescriptionOneOf';
export * from './altNameCreate';
export * from './altNameCreateAllOf';
export * from './altNameCreateAllOfAction';
export * from './altNameDescription';
export * from './altNameDescriptionOneOf';
export * from './characteristic';
export * from './characteristicUnit';
export * from './characteristicUnitOneOf';
export * from './characteristicsResponse';
export * from './image';
export * from './locale';
export * from './localesResponse';
export * from './media';
export * from './mediaOrder';
export * from './mediaOrderOneOf';
export * from './unit';
export * from './unitCaption';
export * from './unitCaptionOneOf';
export * from './unitsResponse';
