/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Common
 */
import type { MediaUpdateOrder } from './mediaUpdateOrder';

export interface MediaUpdate {
  deleted?: boolean;
  filename: string;
  id: string;
  mimetype: string;
  order: MediaUpdateOrder;
  originalName: string;
  path: string;
  size: number;
}
