/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * API Admin
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { UnitCaptionOneOf } from './unitCaptionOneOf';

export type UnitCaption = string | UnitCaptionOneOf;
