version: "3"
name: kitsunaana
services:
  main-db:
    image: postgres
    ports:
      - 5678:5432
    environment:
      - POSTGRES_USER=kitsunaana
      - POSTGRES_PASSWORD=kitsunaana
      - POSTGRES_DB=kitsunaana
    volumes:
      - main-db:/var/lib/postgresql/data
volumes:
  main-db: