/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */

export * from './altName';
export * from './altNameAllOf';
export * from './altNameBase';
export * from './altNameBaseDescription';
export * from './altNameBaseDescriptionOneOf';
export * from './altNameCreate';
export * from './altNameCreateAllOf';
export * from './altNameCreateAllOfAction';
export * from './altNameDescription';
export * from './altNameDescriptionOneOf';
export * from './locale';
export * from './localesResponse';
