/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const getCategoriesResponse = zod.object({
  rows: zod.array(
    zod.object({
      id: zod.number(),
      description: zod.string(),
      caption: zod.string(),
      order: zod.number(),
      altNames: zod.array(
        zod.any().and(
          zod.object({
            id: zod.number(),
          })
        )
      ),
      media: zod.array(
        zod.object({
          id: zod.string(),
          filename: zod.string(),
          originalName: zod.string(),
          path: zod.string(),
          mimetype: zod.string(),
          order: zod.number().or(zod.any().nullable()),
          size: zod.number(),
        })
      ),
    })
  ),
  count: zod.number(),
});

export const createCategoriesBody = zod.object({
  caption: zod.string(),
  description: zod.string(),
  isShowPhotoWithGoods: zod.boolean(),
  bgColor: zod.string(),
  color: zod.string(),
  blur: zod.number(),
  activeImageId: zod.string().or(zod.any().nullable()),
  captionPosition: zod.enum([
    "top-left",
    "top-center",
    "top-right",
    "center-left",
    "center-center",
    "center-right",
    "bottom-left",
    "bottom-center",
    "bottom-right",
  ]),
  altNames: zod.array(
    zod.any().and(
      zod.object({
        id: zod.number().optional(),
        action: zod.enum(["update", "create", "remove"]),
      })
    )
  ),
  characteristics: zod.array(
    zod.object({
      id: zod.number(),
      characteristic: zod.string(),
      unit: zod.string().or(zod.any().nullable()),
      value: zod.string(),
      hideClient: zod.boolean(),
    })
  ),
  media: zod.array(
    zod.object({
      id: zod.string(),
      filename: zod.string(),
      originalName: zod.string(),
      path: zod.string(),
      mimetype: zod.string(),
      order: zod.number().or(zod.any().nullable()),
      size: zod.number(),
    })
  ),
});

export const createCategoriesResponse = zod.object({
  id: zod.number(),
  description: zod.string(),
  caption: zod.string(),
  order: zod.number(),
  altNames: zod.array(
    zod.any().and(
      zod.object({
        id: zod.number(),
      })
    )
  ),
  media: zod.array(
    zod.object({
      id: zod.string(),
      filename: zod.string(),
      originalName: zod.string(),
      path: zod.string(),
      mimetype: zod.string(),
      order: zod.number().or(zod.any().nullable()),
      size: zod.number(),
    })
  ),
});

export const updateCategoryParams = zod.object({
  categoryId: zod.number(),
});

export const updateCategoryResponseItem = zod.number();
export const updateCategoryResponse = zod.array(updateCategoryResponseItem);

export const getCategoryParams = zod.object({
  categoryId: zod.number(),
});

export const getCategoryResponse = zod.object({
  id: zod.number(),
  caption: zod.string(),
  description: zod.string(),
  isShowPhotoWithGoods: zod.boolean(),
  bgColor: zod.string(),
  color: zod.string(),
  blur: zod.number(),
  order: zod.number().optional(),
  activeImageId: zod.string().or(zod.any().nullable()),
  captionPosition: zod.enum([
    "top-left",
    "top-center",
    "top-right",
    "center-left",
    "center-center",
    "center-right",
    "bottom-left",
    "bottom-center",
    "bottom-right",
  ]),
  altNames: zod.array(
    zod.any().and(
      zod.object({
        id: zod.number(),
      })
    )
  ),
  characteristics: zod.array(
    zod.object({
      id: zod.number(),
      characteristic: zod.string(),
      unit: zod.string().or(zod.any().nullable()),
      value: zod.string(),
      hideClient: zod.boolean(),
    })
  ),
  media: zod.array(
    zod.object({
      id: zod.string(),
      filename: zod.string(),
      originalName: zod.string(),
      path: zod.string(),
      mimetype: zod.string(),
      order: zod.number().or(zod.any().nullable()),
      size: zod.number(),
    })
  ),
});
