/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const getCategoriesResponseItem = zod.object({
  id: zod.number(),
  caption: zod.string(),
  description: zod.string(),
  isShowPhotoWithGoods: zod.boolean(),
  bgColor: zod.string(),
  color: zod.string(),
  blur: zod.number(),
  activeImageId: zod.string().or(zod.any().nullable()),
  captionPosition: zod.enum([
    "top-left",
    "top-center",
    "top-right",
    "center-left",
    "center-center",
    "center-right",
    "bottom-left",
    "bottom-center",
    "bottom-right",
  ]),
  altNames: zod.array(
    zod.object({
      id: zod.number(),
      caption: zod.string(),
      description: zod.string().or(zod.any().nullable()),
      locale: zod.any(),
    })
  ),
  characteristics: zod.array(
    zod.object({
      id: zod.number(),
      characteristic: zod.string(),
      unit: zod.string().or(zod.any().nullable()),
      value: zod.string(),
      hideClient: zod.boolean(),
    })
  ),
  media: zod.array(
    zod.object({
      id: zod.string(),
      filename: zod.string(),
      originalName: zod.string(),
      path: zod.string(),
      mimetype: zod.string(),
      order: zod.number().or(zod.any().nullable()),
      size: zod.number(),
    })
  ),
});
export const getCategoriesResponse = zod.array(getCategoriesResponseItem);

export const updateCategoryParams = zod.object({
  categoryId: zod.number(),
});

export const updateCategoryResponseItem = zod.number();
export const updateCategoryResponse = zod.array(updateCategoryResponseItem);

export const getCategoryParams = zod.object({
  categoryId: zod.number(),
});

export const getCategoryResponse = zod.object({
  id: zod.number(),
  caption: zod.string(),
  description: zod.string(),
  isShowPhotoWithGoods: zod.boolean(),
  bgColor: zod.string(),
  color: zod.string(),
  blur: zod.number(),
  activeImageId: zod.string().or(zod.any().nullable()),
  captionPosition: zod.enum([
    "top-left",
    "top-center",
    "top-right",
    "center-left",
    "center-center",
    "center-right",
    "bottom-left",
    "bottom-center",
    "bottom-right",
  ]),
  altNames: zod.array(
    zod.object({
      id: zod.number(),
      caption: zod.string(),
      description: zod.string().or(zod.any().nullable()),
      locale: zod.any(),
    })
  ),
  characteristics: zod.array(
    zod.object({
      id: zod.number(),
      characteristic: zod.string(),
      unit: zod.string().or(zod.any().nullable()),
      value: zod.string(),
      hideClient: zod.boolean(),
    })
  ),
  media: zod.array(
    zod.object({
      id: zod.string(),
      filename: zod.string(),
      originalName: zod.string(),
      path: zod.string(),
      mimetype: zod.string(),
      order: zod.number().or(zod.any().nullable()),
      size: zod.number(),
    })
  ),
});
