/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Good Api
 * Good Api
 * OpenAPI spec version: 1.0.0
 */

export interface CategoryDto {
  caption: string;
  description: string;
  id: number;
  order: number;
}
