/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Good Api
 * Good Api
 * OpenAPI spec version: 1.0.0
 */

export type CreateGoodBodyImagesItem = {
  caption?: string;
  data?: unknown;
  id?: string;
  type?: string;
};
