/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Good Api
 * Good Api
 * OpenAPI spec version: 1.0.0
 */

export type CreateGoodBodyCaptionPosition =
  typeof CreateGoodBodyCaptionPosition[keyof typeof CreateGoodBodyCaptionPosition];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateGoodBodyCaptionPosition = {
  "top-left": "top-left",
  "top-center": "top-center",
  "top-right": "top-right",
  "center-left": "center-left",
  "center-center": "center-center",
  "center-right": "center-right",
  "bottom-left": "bottom-left",
  "bottom-center": "bottom-center",
  "bottom-right": "bottom-right",
} as const
