/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Good Api
 * Good Api
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from "./categoryDto";
import type { Image } from "./image";

export interface CreateGoodBody {
  article: string;
  caption: string;
  category: CategoryDto;
  deliveryTime: string;
  description: string;
  images: Image[];
  isConsumable: boolean;
  isHot: boolean;
  isNew: boolean;
  label: string;
  notCalculation: boolean;
}
