/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Good Api
 * Good Api
 * OpenAPI spec version: 1.0.0
 */
import type { GoodDto } from "./goodDto"

/**
 * Получение всех товаров
 */
export type GetAllGoodsResponse = GoodDto[];
