/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Good Api
 * Good Api
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDto } from "./categoryDto";

export interface GoodDto {
  caption: string;
  category: CategoryDto;
  description: string;
  id: number;
}
