/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Good Api
 * Good Api
 * OpenAPI spec version: 1.0.0
 */

export * from "./categoryDto"
export * from "./createGoodBody"
export * from "./createGoodBodyCaptionPosition"
export * from "./createGoodBodyImagesIds"
export * from "./createGoodBodyImagesItem"
export * from "./getAllGoodsResponse"
export * from "./getByIdGoodResponse"
export * from "./goodDto"
export * from "./image"
