openapi: 3.1.0
info:
  title: API Admin
  description: Category Api
  version: 1.0.0
servers:
  - url: "http://localhost:3333/api"
paths:
  /locales:
    get:
      operationId: getLocales
      tags:
        - locales
      responses:
        200:
          $ref: "#/components/responses/Locales"

components:
  responses:
    Locales:
      description: Получение всех локалей
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Locale"

  schemas:
    Locale:
      type: object
      properties:
        id:
          type: number
        code:
          type: string
        altName:
          type: string
        caption:
          type: string
      required:
        - id
        - code
        - altName
        - caption

    AltNameBase:
      type: object
      properties:
        caption:
          type: string
        description:
          oneOf:
            - type: string
            - type: "null"
        locale:
          $ref: "#/components/schemas/Locale"
      required:
        - caption
        - locale
        - description

    AltNameCreate:
      allOf:
        - $ref: "#/components/schemas/AltNameBase"
        - type: object
          properties:
            id:
              oneOf:
                - type: number
                - type: string
            action:
              type: string
              enum:
                - "update"
                - "create"
                - "remove"
          required:
            - id

    AltName:
      allOf:
        - $ref: "#/components/schemas/AltNameBase"
        - type: object
          properties:
            id:
              type: number
          required:
            - id
