openapi: 3.0.3
info:
  title: Category Api
  description: Category Api
  version: 1.0.0
servers:
  - url: "http://localhost:3333"
paths:
  /categories:
    get:
      operationId: getCategories
      tags:
        - categories
      responses:
        200:
          $ref: "#/components/responses/GetAllCategories"
    post:
      operationId: createCategories
      tags:
        - categories
      requestBody:
        $ref: "#/components/requestBodies/PostCategory"
      responses:
        200:
          $ref: "#/components/responses/PostCategory"

  /categories/{categoryId}:
    patch:
      operationId: updateCategory
      tags:
        - categories
      parameters:
        - $ref: "#/components/parameters/CategoryId"
      responses:
        200:
          $ref: "#/components/responses/PatchCategory"
      requestBody:
        $ref: "#/components/requestBodies/PatchCategory"

    get:
      operationId: getCategory
      tags:
        - categories
      parameters:
        - $ref: "#/components/parameters/CategoryId"
      responses:
        200:
          $ref: "#/components/responses/GetByIdCategory"

components:
  requestBodies:
    PatchCategory:
      description: Редактирование категории
      content:
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/CategoryDto"
              - type: object
                properties:
                  imagesIds:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        caption:
                          type: string
                      required:
                        - id
                        - caption
                  images:
                    type: array
                    items:
                      type: string
                      format: binary
                required:
                  - imagesIds
                  - images

    PostCategory:
      description: Создание категории
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CategoryCreate"

  responses:
    PostCategory:
      description: Созданная категория
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CategoryPreview"

    GetAllCategories:
      description: Получение всех категорий
      content:
        application/json:
          schema:
            type: object
            properties:
              rows:
                type: array
                items:
                  $ref: "#/components/schemas/CategoryPreview"
              count:
                type: number
            required:
              - rows
              - count

    GetByIdCategory:
      description: Получение категории по id
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CategoryDto"

    PatchCategory:
      description: Изменение категории
      content:
        application/json:
          schema:
            type: array
            items:
              type: number

  parameters:
    CategoryId:
      in: path
      name: categoryId
      required: true
      schema:
        type: number

  schemas:
    CategoryPreview:
      type: object
      properties:
        id:
          type: number
        description:
          type: string
        caption:
          type: string
        order:
          type: number
        altNames:
          type: array
          items:
            $ref: "./alt-name.yaml#/components/schemas/AltName"
        media:
          type: array
          items:
            $ref: "./media.yaml#/components/schemas/Media"
      required:
        - id
        - description
        - caption
        - order
        - altNames
        - media

    CategoryBase:
      type: object
      properties:
        caption:
          type: string
        description:
          type: string
        isShowPhotoWithGoods:
          type: boolean
        bgColor:
          type: string
        color:
          type: string
        blur:
          type: number
        activeImageId:
          oneOf:
            - type: string
            - nullable: true
        captionPosition:
          $ref: "#/components/schemas/CaptionPosition"

        altNames:
          type: array
          items:
            $ref: "./alt-name.yaml#/components/schemas/AltNameCreate"

        characteristics:
          type: array
          items:
            $ref: "./characteristic.yaml#/components/schemas/Characteristic"

        media:
          type: array
          items:
            $ref: "./media.yaml#/components/schemas/Media"
      required:
        - caption
        - description
        - isShowPhotoWithGoods
        - bgColor
        - color
        - blur
        - activeImageId
        - captionPosition
        - altNames
        - characteristics
        - media

    CategoryDto:
      type: object
      properties:
        id:
          type: number
        caption:
          type: string
        description:
          type: string
        isShowPhotoWithGoods:
          type: boolean
        bgColor:
          type: string
        color:
          type: string
        blur:
          type: number
        order:
          type: number
        activeImageId:
          oneOf:
            - type: string
            - nullable: true
        captionPosition:
          $ref: "#/components/schemas/CaptionPosition"
        altNames:
          type: array
          items:
            $ref: "./alt-name.yaml#/components/schemas/AltName"
        characteristics:
          type: array
          items:
            $ref: "./characteristic.yaml#/components/schemas/Characteristic"
        media:
          type: array
          items:
            $ref: "./media.yaml#/components/schemas/Media"
      required:
        - id
        - caption
        - description
        - isShowPhotoWithGoods
        - bgColor
        - color
        - blur
        - activeImageId
        - captionPosition
        - altNames
        - characteristics
        - media

    CategoryCreate:
      type: object
      properties:
        caption:
          type: string
        description:
          type: string
        isShowPhotoWithGoods:
          type: boolean
        bgColor:
          type: string
        color:
          type: string
        blur:
          type: number
        activeImageId:
          oneOf:
            - type: string
            - nullable: true
        captionPosition:
          $ref: "#/components/schemas/CaptionPosition"
        altNames:
          type: array
          items:
            $ref: "./alt-name.yaml#/components/schemas/AltNameCreate"

        characteristics:
          type: array
          items:
            $ref: "./characteristic.yaml#/components/schemas/Characteristic"
        media:
          type: array
          items:
            $ref: "./media.yaml#/components/schemas/Media"
      required:
        - id
        - caption
        - description
        - isShowPhotoWithGoods
        - bgColor
        - color
        - blur
        - activeImageId
        - captionPosition
        - altNames
        - characteristics
        - media

    CaptionPosition:
      type: string
      enum:
        - "top-left"
        - "top-center"
        - "top-right"
        - "center-left"
        - "center-center"
        - "center-right"
        - "bottom-left"
        - "bottom-center"
        - "bottom-right"

    CategoryUpdateDto:
      allOf:
        - $ref: "#/components/schemas/CategoryDto"
        - type: object
          properties:
            imagesIds:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  caption:
                    type: string
                required:
                  - id
                  - caption
            images:
              type: array
              items:
                $ref: "./media.yaml#/components/schemas/Image"

          required:
            - imagesIds
            - images
