openapi: 3.0.3
info:
  title: API Admin
  description: Category Api
  version: 1.0.0
servers:
  - url: "http://localhost:3333/api"

paths:
  /characteristics:
    get:
      operationId: getCharacteristics
      tags:
        - characteristics
      responses:
        200:
          $ref: "#/components/responses/Characteristics"

  /units:
    get:
      operationId: getUnits
      tags:
        - units
      responses:
        200:
          $ref: "#/components/responses/Units"

components:
  responses:
    Characteristics:
      description: Получение всех характеристик
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Characteristic"

    Units:
      description: Получение всех единиц измерения
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Unit"

  schemas:
    Unit:
      type: object
      properties:
        id:
          type: string
        caption:
          oneOf:
            - type: string
            - nullable: true
      required:
        - id
        - caption

    CharacteristicBase:
      type: object
      properties:
        characteristic:
          type: string
        unit:
          oneOf:
            - type: string
            - nullable: true
        value:
          type: string
        hideClient:
          type: boolean
      required:
        - id
        - characteristic
        - value
        - hideClient
        - unit

    CharacteristicCreate:
      allOf:
        - $ref: "#/components/schemas/CharacteristicBase"
        - type: object
          properties:
            action:
              type: string
              enum:
                - create
                - update
                - remove
            id:
              type: number
          required:
            - action

    Characteristic:
      allOf:
        - $ref: "#/components/schemas/CharacteristicBase"
        - type: object
          properties:
            id:
              type: number
          required:
            - id
