/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryUpdateActiveImageId } from './categoryUpdateActiveImageId';
import type { AltNameCreate } from './alt-name/altNameCreate';
import type { CaptionPosition } from './captionPosition';
import type { CharacteristicCreate } from './characteristic/characteristicCreate';
import type { CategoryUpdateDescription } from './categoryUpdateDescription';
import type { Image } from './media/image';
import type { MediaCreate } from './media/mediaCreate';
import type { CategoryUpdateOrder } from './categoryUpdateOrder';
import type { TagCreate } from './tagCreate';

export interface CategoryUpdate {
  activeImageId: CategoryUpdateActiveImageId;
  altNames: AltNameCreate[];
  bgColor: string;
  blur: number;
  caption: string;
  captionPosition: CaptionPosition;
  characteristics: CharacteristicCreate[];
  color: string;
  description: CategoryUpdateDescription;
  images: Image[];
  isShowPhotoWithGoods: boolean;
  media: MediaCreate[];
  order: CategoryUpdateOrder;
  tags: TagCreate[];
}
