/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryUpdateWithMediaActiveImageId } from './categoryUpdateWithMediaActiveImageId';
import type { AltNameCreate } from './alt-name/altNameCreate';
import type { CaptionPosition } from './captionPosition';
import type { CharacteristicCreate } from './characteristic/characteristicCreate';
import type { CategoryUpdateWithMediaDescription } from './categoryUpdateWithMediaDescription';
import type { Media } from './media/media';
import type { CategoryUpdateWithMediaOrder } from './categoryUpdateWithMediaOrder';
import type { TagCreate } from './tagCreate';

export interface CategoryUpdateWithMedia {
  activeImageId: CategoryUpdateWithMediaActiveImageId;
  altNames: AltNameCreate[];
  bgColor: string;
  blur: number;
  caption: string;
  captionPosition: CaptionPosition;
  characteristics: CharacteristicCreate[];
  color: string;
  description: CategoryUpdateWithMediaDescription;
  isShowPhotoWithGoods: boolean;
  media: Media[];
  order?: CategoryUpdateWithMediaOrder;
  tags: TagCreate[];
}
