/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryFieldsDescription } from "./categoryFieldsDescription";

export interface CategoryFields {
  bgColor: string;
  blur: number;
  caption: string;
  color: string;
  description: CategoryFieldsDescription;
  isShowPhotoWithGoods: boolean;
}
