/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryBaseActiveImageId } from "./categoryBaseActiveImageId";
import type { CaptionPosition } from "./captionPosition";
import type { Media } from "./media/media";

export interface CategoryBase {
  activeImageId: CategoryBaseActiveImageId;
  bgColor: string;
  blur: number;
  caption: string;
  captionPosition: CaptionPosition;
  color: string;
  description: string;
  isShowPhotoWithGoods: boolean;
  media: Media[];
}
