/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { AltName } from "./alt-name/altName";
import type { Media } from "./media/media";
import type { CategoryPreviewOrder } from "./categoryPreviewOrder";

export interface CategoryPreview {
  altNames: AltName[];
  caption: string;
  description: string;
  id: number;
  media: Media[];
  order: CategoryPreviewOrder;
}
