/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { AltName } from "./alt-name/altName"
import type { Characteristic } from "./characteristic/characteristic"
import type { CategoryDtoAllOfOrder } from "./categoryDtoAllOfOrder"
import type { Tag } from "./tag"

export type CategoryDtoAllOf = {
  altNames: AltName[];
  characteristics: Characteristic[];
  id: number;
  order: CategoryDtoAllOfOrder;
  tags: Tag[];
};
