/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryCreateWithMediaActiveImageId } from "./categoryCreateWithMediaActiveImageId"
import type { AltNameCreate } from "./alt-name/altNameCreate"
import type { CaptionPosition } from "./captionPosition"
import type { CharacteristicCreate } from "./characteristic/characteristicCreate"
import type { CategoryCreateWithMediaDescription } from "./categoryCreateWithMediaDescription"
import type { Media } from "./media/media"
import type { TagCreate } from "./tagCreate"

export interface CategoryCreateWithMedia {
  activeImageId: CategoryCreateWithMediaActiveImageId;
  altNames: AltNameCreate[];
  bgColor: string;
  blur: number;
  caption: string;
  captionPosition: CaptionPosition;
  characteristics: CharacteristicCreate[];
  color: string;
  description: CategoryCreateWithMediaDescription;
  isShowPhotoWithGoods: boolean;
  media: Media[];
  tags: TagCreate[];
}
