/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { AltNameCreate } from "./alt-name/altNameCreate"
import type { CharacteristicCreate } from "./characteristic/characteristicCreate"
import type { Image } from "./media/image"
import type { TagCreate } from "./tagCreate"

export type CategoryUpdateDtoAllOf = {
  altNames: AltNameCreate[];
  characteristics: CharacteristicCreate[];
  images: Image[];
  tags: TagCreate[];
};
