/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { TagBase } from "./tagBase";
import type { TagAllOf } from "./tagAllOf";

export type Tag = TagBase & TagAllOf;
