/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { TagCreateAllOfAction } from "./tagCreateAllOfAction";
import type { TagCreateAllOfId } from "./tagCreateAllOfId";

export type TagCreateAllOf = {
  action?: TagCreateAllOfAction;
  id: TagCreateAllOfId;
};
