/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */

export type TagCreateAllOfAction =
  typeof TagCreateAllOfAction[keyof typeof TagCreateAllOfAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TagCreateAllOfAction = {
  create: "create",
  update: "update",
  remove: "remove",
} as const
