/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * API Admin
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { AltNameBase } from "./altNameBase"
import type { AltNameCreateAllOf } from "./altNameCreateAllOf"

export type AltNameCreate = AltNameBase & AltNameCreateAllOf;
