/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 */
import type { AltNameDescriptionOneOf } from "./altNameDescriptionOneOf";

export type AltNameDescription = string | AltNameDescriptionOneOf;
