/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * API Admin
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { AltNameBaseDescription } from "./altNameBaseDescription";
import type { Locale } from "./locale";

export interface AltNameBase {
  caption: string;
  description: AltNameBaseDescription;
  locale: Locale;
}
