/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * API Admin
 * Category Api
 * OpenAPI spec version: 1.0.0
 */

export type AltNameCreateAllOfAction =
  typeof AltNameCreateAllOfAction[keyof typeof AltNameCreateAllOfAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AltNameCreateAllOfAction = {
  update: "update",
  create: "create",
  remove: "remove",
} as const;
