/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 */
import type { AltNameDescription } from "./altNameDescription";
import type { Locale } from "./locale";

export interface AltName {
  caption: string;
  description: AltNameDescription;
  id: number;
  locale: Locale;
}
