/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * API Admin
 * Category Api
 * OpenAPI spec version: 1.0.0
 */

export type CharacteristicCreateAllOfAction =
  typeof CharacteristicCreateAllOfAction[keyof typeof CharacteristicCreateAllOfAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CharacteristicCreateAllOfAction = {
  create: "create",
  update: "update",
  remove: "remove",
} as const
