/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Common
 */
import type { MediaOrder } from "./mediaOrder";

export interface Media {
  filename: string;
  id: string;
  mimetype: string;
  order: MediaOrder;
  originalName: string;
  path: string;
  size: number;
}
