/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * API Admin
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { Unit } from "./unit";

/**
 * Получение всех единиц измерения
 */
export type UnitsResponse = Unit[];
