export const menu = [
  {
    id: 0,
    name: "catalog",
    path: "catalog",
    caption: "Каталог",
    icon: "catalog",
    sublist: [
      {
        id: 1,
        name: "goods",
        path: "goods",
        caption: "Товары",
        icon: "goods",
        disabled: true,
      },
      {
        id: 2,
        name: "additions",
        path: "additions",
        caption: "Дополнения",
        disabled: true,
        icon: "additional",
      },
    ],
  },
  {
    id: 8,
    name: "stopList",
    path: "stop-list",
    caption: "Стоп-лист",
    icon: "stopList",
    sublist: [],
  },
  {
    id: 9,
    name: "pricing",
    path: "pricing",
    caption: "Ценообразование",
    disabled: true,
    icon: "pricing",
    sublist: [
      {
        id: 10,
        name: "priceList",
        path: "price-list",
        caption: "Прайс-лист",
        disabled: true,
        icon: "priceList",
      },
      {
        id: 12,
        name: "promoCode",
        path: "promo-code",
        caption: "Промокоды",
        icon: "promoCode",
        disabled: true,
      },
    ],
  },
  {
    id: 13,
    name: "order",
    path: "order",
    caption: "Заказы",
    icon: "orders",
    disabled: true,
    sublist: [
      {
        id: 14,
        name: "newOrder",
        path: "new-order",
        caption: "Новый заказ",
        icon: "newOrder",
        disabled: true,
      },
    ],
  },
  {
    id: 16,
    name: "clients",
    path: "clients",
    caption: "Клиенты",
    icon: "clients",
    disabled: true,
    sublist: [
      {
        id: 17,
        name: "analysis",
        path: "analysis",
        caption: "Анализ",
        disabled: true,
        icon: "analysis",
      },
      {
        id: 18,
        name: "chat",
        path: "chat",
        caption: "Чаты",
        disabled: true,
        icon: "chat",
      },
      {
        id: 19,
        name: "favorite",
        path: "favorite",
        caption: "Избранное",
        disabled: true,
        icon: "favorite",
      },
    ],
  },
]

export const menuBottom = [
  {
    id: 30,
    name: "users",
    path: "users",
    icon: "users",
    caption: "Пользователи",
    disabled: true,
    sublist: [
      {
        id: 31,
        name: "settings",
        path: "settings",
        icon: "settings",
        caption: "Настройки",
      },
    ],
  },
]
