/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * API Admin
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const getCharacteristicsResponseItem = zod
  .object({
    caption: zod.string().optional(),
    unit: zod.string().or(zod.null()),
    value: zod.string(),
    hideClient: zod.boolean(),
  })
  .and(
    zod.object({
      id: zod.number(),
    })
  );
export const getCharacteristicsResponse = zod.array(
  getCharacteristicsResponseItem
);

export const getUnitsResponseItem = zod.object({
  id: zod.number(),
  caption: zod.string().or(zod.null()),
});
export const getUnitsResponse = zod.array(getUnitsResponseItem);
