/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * API Admin
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const getCharacteristicsResponseItem = zod.object({
  id: zod.number(),
  characteristic: zod.string(),
  unit: zod.string().or(zod.any().nullable()),
  value: zod.string(),
  hideClient: zod.boolean(),
});
export const getCharacteristicsResponse = zod.array(
  getCharacteristicsResponseItem
);

export const getUnitsResponseItem = zod.object({
  id: zod.string(),
  caption: zod.string().or(zod.any().nullable()),
});
export const getUnitsResponse = zod.array(getUnitsResponseItem);
