/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Category Api
 * Category Api
 * OpenAPI spec version: 1.0.0
 */
import type { CharacteristicBase } from "./characteristicBase"
import type { CharacteristicCreateAllOf } from "./characteristicCreateAllOf"

export type CharacteristicCreate = CharacteristicBase &
  CharacteristicCreateAllOf;
